name: rgcn
hidden_dim: 64
num_layers: 3
dropout: 0.2
batch_norm: true
activation: relu
aggr: sum #how to join the messages from different edge types, can be sum, mean, max
heads: 4
use_residual: true #whether to use residual connections between layers
conv_type: rgcn
num_bases: 8