defaults:
  - data: ogb_dataset
  - model: gcn
  - _self_

training:
  lr: 0.001
  epochs: 20
  batch_size: 32
  optimizer: adam
  to_undirected: true

wandb:
  project: "politechnika-gnn-thesis"
  entity: "politechnika-gnn-thesis"