defaults:
  - data: ogb_dataset
  - model: gcn
  - _self_

training:
  lr: 0.001
  epochs: 20
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.2
  pooling: mean
  batch_norm: true
  conv_type: gcn

meta:
  owner_initials: "mo"

wandb:
  project: "politechnika-gnn-thesis"
  entity: "politechnika-gnn-thesis"