defaults:
  - data: dataset_syn
  - model: null
  - _self_

training:
  lr: 0.001
  epochs: 20
  batch_size: 32 #for now full batch, we need to adjust models
  optimizer: adam
  seed: 42
  eval_per_endpoint: true
  early_stopping_patience: 100
  early_stopping_min_delta: 0.000
  weight_decay: 0.0005
  oversmoothing_excluded_models: ["linear"]
  auto_threshold: true
  eval_threshold: 0.5
  selection_metric: "auprc"
  track_oversmoothing: true
  oversmoothing_sample_size: 2000
  grad_clip: 0.0
  oversmoothing_per_layer: true                 # by default: false
  oversmoothing_per_layer_detail: false         # true - including node type
  oversmoothing_per_layer_sample_size: 1000 
  loss_type: bce          # bce default, focal
  focal_gamma: 2.0
  focal_use_alpha: true
  pos_weight_cap: 30.0  

meta:
  owner_initials: "MO" #our names initials to recognize the experiments in wandb

wandb:
  project: "politechnika-gnn-thesis"
  entity: "politechnika-gnn-thesis"